apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ovby
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0006-tenant/cin4s-839-0006-app/devfile-sample-ovby@sha256:cd0e84511c1811b9fc48ac1fac338a1ff3ba77d29de5e55e79864e160ad33a8e
        name: my-nodejs
        resources: {}
status: {}
